export const actionConstants = {
    RECIEVED_LOGIN_USER: "RECIEVED_LOGIN_USER",
    REQUEST_LOGIN_USER: "REQUEST_LOGIN_USER",

    RECIEVED_LOGOUT_USER: "RECIEVED_LOGOUT_USER",
    REQUEST_LOGOUT_USER: " REQUEST_LOGOUT_USER",

    RECIEVED_VERSION_INFO: "RECIEVED_VERSION_INFO",
    REQUEST_VERSION_INFO: "RECIEVED_VERSION_INFO",

    RECIEVED_HEADER_PARAMS: "RECIEVED_HEADER_PARAMS",
    REQUEST_HEADER_PARAMS: "REQUEST_HEADER_PARAMS",

    UPDATED_STORE_ID: "UPDATED_STORE_ID",
    UPDATE_STORE_ID: "UPDATE_STORE_ID",

    RECIEVED_IP: "RECIEVED_IP",
    REQUEST_IP: "REQUEST_IP",

    RECIEVED_ITEM_STATUS: "RECIEVED_ITEM_STATUS",
    REQUEST_ITEM_STATUS: "REQUEST_ITEM_STATUS",

    UPDATED_CUST_INFO: "UPDATED_CUST_INFO",
    UPDATE_CUST_INFO: " UPDATE_CUST_INFO",

    RECIEVED_NEW_CUSTOMER: "RECIEVED_NEW_CUSTOMER",
    REQUEST_NEW_CUSTOMER: "REQUEST_NEW_CUSTOMER",

    RECIEVED_DL_CUSTOMER: "RECIEVED_DL_CUSTOMER",
    REQUEST_DL_CUSTOMER: "REQUEST_DL_CUSTOMER",

    RECIEVED_SEARCH_CUSTOMER: "RECIEVED_SEARCH_CUSTOMER",
    REQUEST_SEARCH_CUSTOMER: "REQUEST_SEARCH_CUSTOMER",

    RECIEVED_UPDATE_RENTAL_DETAIL: "RECIEVED_UPDATE_RENTAL_DETAIL",
    REQUEST_UPDATE_RENTAL_DETAIL: "REQUEST_UPDATE_RENTAL_DETAIL",

    RECEIVED_FILLING_RENTAL_INFO: "RECEIVED_FILLING_RENTAL_INFO",
    REQUEST_FILLING_RENTAL_INFO: "REQUEST_FILLING_RENTAL_INFO",

    RECEIVED_BLOCK_RENTAL_ITEM: "RECEIVED_BLOCK_RENTAL_ITEM",
    REQUEST_BLOCK_RENTAL_ITEM: "REQUEST_BLOCK_RENTAL_ITEM",

    RECEIVED_RETRIVE_RENTAL_IMAGES: "RECEIVED_RETRIVE_RENTAL_IMAGES",
    REQUEST_RETRIVE_RENTAL_IMAGES: "REQUEST_RETRIVE_RENTAL_IMAGES",

    RECEIVED_UPLOAD_IMAGES: "RECEIVED_UPLOAD_IMAGES",
    REQUEST_UPLOAD_IMAGES: "REQUEST_UPLOAD_IMAGES",

    RECEIVED_INSPECTION_QUESTIONS: "RECEIVED_INSPECTION_QUESTIONS",
    REQUEST_INSPECTION_QUESTIONS: "REQUEST_INSPECTION_QUESTIONS",

    SYSTEM_ERROR: "SYSTEM_ERROR",
    SYSTEM_ERROR_ITEMSTATUS: "SYSTEM_ERROR_ITEMSTATUS",
    SYSTEM_ERROR_TERMSANDCONDITIONS: "SYSTEM_ERROR_TERMSANDCONDITIONS",
    SYSTEM_ERROR_SEARCH_CUST: "SYSTEM_ERROR_SEARCH_CUST",
    SYSTEM_ERROR_SAVEIMAGE: "SYSTEM_ERROR_SAVEIMAGE",
    SYSTEM_ERROR_NEW_CUSTOMER: "SYSTEM_ERROR_NEW_CUSTOMER",
    SYSTEM_ERROR_UPDATE_CUSTOMER: "SYSTEM_ERROR_UPDATE_CUSTOMER",
    SYSTEM_ERROR_UPDATE_RENT_DETAILS: "SYSTEM_ERROR_UPDATE_RENT_DETAILS",
    SYSTEM_ERROR_HEADER_PARAMS: "SYSTEM_ERROR_HEADER_PARAMS",
    SYSTEM_ERROR_RETRIEVE_QSNS: "SYSTEM_ERROR_RETRIEVE_QSNS",
    SYSTEM_ERROR_GET_AGREEMENT_NO: "SYSTEM_ERROR_GET_AGREEMENT_NO",
    SYSTEM_ERROR_UPDATE_QSNS: "SYSTEM_ERROR_UPDATE_QSNS",
    SYSTEM_ERROR_APP_DETAILS: "SYSTEM_ERROR_APP_DETAILS",
    SYSTEM_ERROR_CUSTOMER_INFO: "SYSTEM_ERROR_CUSTOMER_INFO",
    SYSTEM_ERROR_UPDATE_RETURN_DETAILS: "SYSTEM_ERROR_UPDATE_RETURN_DETAILS",
    SYSTEM_ERROR_CANCEL_RENT_RETURN: "SYSTEM_ERROR_CANCEL_RENT_RETURN",
    SYSTEM_ERROR_FILLINGRENTAL: "SYSTEM_ERROR_FILLINGRENTAL",
    SYSTEM_ERROR_BLOCK_ITEM: "SYSTEM_ERROR_BLOCK_ITEM",

    NETWORK_ERROR: "NETWORK_ERROR",

    EMPTY_REDUCER: "EMPTY_REDUCER",

    FLAG_RESET: "FLAG_RESET",

    SYSTEM_ERROR_EXTENDITEM: "SYSTEM_ERROR_EXTENDITEM",

    RECIEVED_TRAILER_TYPE_DETAIL: "RECIEVED_TRAILER_TYPE_DETAIL",
    REQUEST_TRAILER_TYPE_DETAIL: "REQUEST_TRAILER_TYPE_DETAIL",

    RECIEVED_CURRENT_RENTALS: "RECIEVED_CURRENT_RENTALS",
    REQUEST_CURRENT_RENTALS: "REQUEST_CURRENT_RENTALS",

    RECIEVED_PRE_RENTAL_INFO: "RECIEVED_PRE_RENTAL_INFO",
    REQUEST_PRE_RENTAL_INFO: "REQUEST_PRE_RENTAL_INFO",

    SAVED_PRE_RENTAL_INFO_IMAGES: 'SAVED_PRE_RENTAL_INFO_IMAGES',
    SAVE_PRE_RENTAL_INFO_IMAGES: 'SAVE_PRE_RENTAL_INFO_IMAGES',

    UPDATED_INSPECTION_QUESTIONS: "UPDATED_INSPECTION_QUESTIONS",
    UPDATE_INSPECTION_QUESTIONS: "UPDATE_INSPECTION_QUESTIONS",

    RECEIVED_RETURN_INSPECTION_DETAILS: "RECEIVED_RETURN_INSPECTION_DETAILS",
    REQUEST_RETURN_INSPECTION_DETAILS: "REQUEST_RETURN_INSPECTION_DETAILS",

    REQUEST_TERMS_AND_CONDITIONS: "REQUEST_TERMS_AND_CONDITIONS",
    RECIEVED_TERMS_AND_CONDITIONS: "RECIEVED_TERMS_AND_CONDITIONS",

    REQUEST_RENTAL_AGREEMENT_NUMBER: "REQUEST_RENTAL_AGREEMENT_NUMBER",
    RECIEVED_RENTAL_AGREEMENT_NUMBER: "RECIEVED_RENTAL_AGREEMENT_NUMBER",

    REQUEST_EXTEND_ITEM_RENTAL: "REQUEST_EXTEND_ITEM_RENTAL",
    RECEIVED_EXTEND_ITEM_RENTAL: "RECEIVED_EXTEND_ITEM_RENTAL",

    REQUEST_RETRIEVE_STORE_INFO: "REQUEST_RETRIEVE_STORE_INFO",
    RECEIVED_RETRIEVE_STORE_INFO: "RECEIVED_RETRIEVE_STORE_INFO",

    SAVED_CUST_INSURANCE_IMAGES: 'SAVED_CUST_INSURANCE_IMAGES',
    SAVE_CUST_INSURANCE_IMAGES: 'SAVE_CUST_INSURANCE_IMAGES',

    REQUEST_RETRIEVE_RENT_DURATION: "REQUEST_RETRIEVE_RENT_DURATION",
    RECEIVED_RETRIEVE_RENT_DURATION: "RECEIVED_RETRIEVE_RENT_DURATION",

    REQUEST_RETRIEVE_STORE_TIMING: "REQUEST_RETRIEVE_STORE_TIMING",
    RECEIVED_RETRIEVE_STORE_TIMING: "RECEIVED_RETRIEVE_STORE_TIMING",

    REQUEST_RETRIEVE_DELETE_IMAGE: "REQUEST_RETRIEVE_DELETE_IMAGE",
    RECEIVED_RETRIEVE_DELETE_IMAGE: "RECEIVED_RETRIEVE_DELETE_IMAGE",

    REQUEST_CANCEL_RENT_RETURN: "REQUEST_CANCEL_RENT_RETURN",
    RECIEVED_CANCEL_RENT_RETURN: "RECIEVED_CANCEL_RENT_RETURN",

    REQUEST_UPDATE_RETURN_DETAIL: "REQUEST_UPDATE_RETURN_DETAIL",
    RECIEVED_UPDATE_RETURN_DETAIL: "RECIEVED_UPDATE_RETURN_DETAIL",

    RECIEVED_APP_DETAILS: "RECIEVED_APP_DETAILS",
    REQUEST_APP_DETAILS: "REQUEST_APP_DETAILS",

    RECIEVED_CUSTOMER_INFO: "RECIEVED_CUSTOMER_INFO",
    REQUEST_CUSTOMER_INFO: "REQUEST_CUSTOMER_INFO",

    EMPTY_IMAGE_REDUCER: "EMPTY_IMAGE_REDUCER",
    NETWORK_ERROR_DLSCREEN: "NETWORK_ERROR_DLSCREEN",

    RECIEVED_PRE_RETURN_INFO: "RECIEVED_PRE_RETURN_INFO",
    REQUEST_PRE_RETURN_INFO: "REQUEST_PRE_RETURN_INFO",

    SYSTEM_ERROR_UPLOAD_IMAGE: "SYSTEM_ERROR_UPLOAD_IMAGE",
    SYSTEM_ERROR_UPLOAD_DELETE_IMAGE: "SYSTEM_ERROR_UPLOAD_DELETE_IMAGE",
    SYSTEM_ERROR_RETURN_INFO: "SYSTEM_ERROR_RETURN_INFO",

    RECIEVED_RENT_DATA_CLEAR: "RECIEVED_RENT_DATA_CLEAR",
    REQUEST_RENT_DATA_CLEAR: "REQUEST_RENT_DATA_CLEAR",

    RECIEVED_RETURN_DATA_CLEAR: "RECIEVED_RETURN_DATA_CLEAR",
    REQUEST_RETURN_DATA_CLEAR: "REQUEST_RETURN_DATA_CLEAR",

    RECIEVED_EXTEND_DATA_CLEAR: "RECIEVED_EXTEND_DATA_CLEAR",
    REQUEST_EXTEND_DATA_CLEAR: "REQUEST_EXTEND_DATA_CLEAR"


};